Makefile
package/staging2testing

staging2testing outputs the to be executed commands for a todolist which
can be moved to [testing].
Signed-off-by: Jelle van der Waa <jelle@archlinux.org>

Add tool to generate dbscripts commands for todolists

---

package/diffcabal

Simple tool to compare upstream revision 0 cabal files to find out what changed. This can ease maintaining of Haskell libraries and avoid missing any dependency changes.

Add diffcabal

---

package/diffpypi

Simple tool to compare metadata file for PyPI projects. This can ease
maintenance of Python libraries/projects just like diffcabal, by
downloading and comparing for metadata changes so they are not
overlooked which resulting in broken packages.

Add diffpypi

---

admin/checkservices

The command in [get_services](https://github.com/archlinux/contrib/blob/master/admin/checkservices#L93-L96):
systemctl --no-legend --full --type service --state running|cut -f1 -d' '
The `cut` worked up to systemd 245.7 which printed something like this:
```
$ systemctl --no-legend --full --type service --state running
systemd-journald.service  loaded active running Journal Service
systemd-logind.service    loaded active running Login Service
systemd-networkd.service  loaded active running Network Service
systemd-resolved.service  loaded active running Network Name Resolution
systemd-timesyncd.service loaded active running Network Time Synchronization
systemd-udevd.service     loaded active running udev Kernel Device Manager
```
But systemd 246.1 adds leading spaces (or, more exactly, …

checkservices: fix parsing of systemctl command for version 246.1

---

security/repo-sec-checker

repo_sec_checker scans all repository's for missing hardening bits. The
tool currently supports relro, stack canary, nx, pie, rpath, runpath and
fortify. The output is currently limited to a table view , which can
later be expanded to JSON output.

Add repo_sec_checker tool

---

package/staging2testing

Running db-move multiple times could lead to breakage due to repository
being inconsistent for the time being. This change merges all pkgbases
of the same repo to a single command so each db itself is always
consistent.

staging2testing: Merge commands to avoid breakage

---

package/diffpypi

1. Why is this change neccesary?
Because we needed to double quote the variables we're using to prevent globbing
and word splitting and we needed to add return values when executing a command
in case the command fails.
2. How does it address the issue?
By double quoting the variables and adding an OR to the commands that can fail.
3. What side effects does this change have?
Closes #36.

Added double quotes to vars and exit for commands.

---

security/compose-asa

The old alias is deprecated and will be removed soon, cf. https://lists.archlinux.org/pipermail/arch-dev-public/2021-June/030462.html

[compose-asa] update mailing list address

---

package/parse-submodules

In order the clarify the usage of the `parse-submodules` output:
- "sources array" phrase is replaced with "source array" and same is applied for `source=()`, which was previously `sources=()"`
- The echo message that points out the required update of `prepare()` function is also made more clear.

Update parse-submodules output messages

---

package/parse-submodules

`parse-submodules` will now honour the type of input git reference and include it correctly in the source array for the VCS fragment string.

[parse-submodules] make sure VCS fragment string matches input type: tag, branch, commit

---

package/parse-submodules

Make sure `parse-submodules` produces consistent output to work better with `diff`, improve readability and tooling.

[parse-submodules] Make sure output is sorted for consistency

---

admin/checkservices

This avoids silly errors like
```
$ checkservices -h
Error:: You need to be root
```

checkservices: do not require running as root to parse cli options

---

package/parse-submodules

The upstream source URL currently appears incorrectly, missing the `git+` or `git://` prefix in particular necessary situations as per the `PKGBUILD` specification. This PR resolves this issue.
Also:
- make sure functions do not have underscores in their names to avoid variable confusion
- small abstractions
- fix a typo in `existence`

Fix source upstream URL

---

package/cleanup-list

Hello there! I've added some type hints to the cleanup-list python script to make development easier. I plan on adding type hints to all functions in all python scripts in the repo(so I wouldn't merge yet).
Have a Great Day!

Add type hints to all functions in cleanup-list script

---

package/rebuild-todo

One of the example shown in the rebuild-todo's help message incorrectly mentions [extra-testing] as the repo target instead of [core-staging].

Fix typo in rebuild-todo's help message/example

---

package/rebuild-todo

- Print a message during the packages list parsing (to avoid thinking the script is just stuck) 
- Improve the "confirm" message: fixes https://github.com/archlinux/contrib/issues/54
- Don't exit on failed release
- Show the exact list of skipped packages (that failed to build), rebuilt packages (but unreleased) and released packages when done: fixes https://github.com/archlinux/contrib/issues/53

rebuild-todo: Various improvements

---

package/rebuild-todo

Use the -o/--offload flag to use offloaded builds in rebuild-todo (via pkgctl build -o/--offload)

Add -o/--offload support to rebuild-todo

---

admin/checkservices

Fixes https://github.com/archlinux/contrib/issues/68

Don't enforce white color, use terminal default instead

---

admin/checkservices

This commit adds support for services with a delegate cgroup subhierarchy and introduces the `-m/-M` option to include or not services in `machine.slice` (default is no).
Parts of the patch are taken from https://github.com/archlinux/contrib/issues/61#issuecomment-1986888476 & https://github.com/archlinux/contrib/issues/61#issuecomment-2211966735
Fixes https://github.com/archlinux/contrib/issues/61

Add support for services with a delegate cgroup subhierarchy in checkservices + ignore services in machine.slice by default

---

admin/checkservices

This commit aims to introduce an ignored service list that contains services that are known to cause parsing errors and/or issues when being restarted. Elements can be added to the list with the `-i "service_name".service` option (e.g. `checkservices -i sddm.service -i NetworkManager.service`)
Show usage and exit if the `-i` argument does not finish with `.service` (to ensure a precise parsing and avoid unexpected filtering)
Fixes https://github.com/archlinux/contrib/issues/44

Add a configurable "ignored service" list to checkservices

---

admin/checkservices

Even though the -R flag were parsed it were not honored and there was no way to skip being asked for restart with the -R flag. Useful for putting checkservices in an alpm hook.

checkservices: honor -R flag

---

admin/checkservices

Add the missing -m/-M options to getops.
Fixes https://github.com/archlinux/contrib/pull/79#issuecomment-2241095972

checkservices: honor -m/-M flags

---

Makefile
package/pkggrep

sogrep covers most use-cases but sometimes one wants to look for a
specific symbol. This script was originally written by foutrelis.
Signed-off-by: Christian Heusel <christian@heusel.eu>

Add pkggrep: script for grepping for an exact symbol

---

package/rebuild-todo

The script also accepts `-d` as a short option for `--dry-run`

rebuild-todo: Fix documentation for -d / --dry-run

---

package/rebuild-todo

Allows to import PGP keys for packages source verification into the user's keyring before rebuilding packages (including support for offloaded builds).

rebuild-todo: Add the --import-keys option

---

package/rebuild-todo

The former is irrelevant / useless since we now use 'pkgctl --rebuild'
The latter just isn't a thing anymore

rebuild-todo: Remove deprecated 'bump_pkgrel' function and '--no-bump' option

---

Makefile
package/greposcope

> Usage: greposcope [OPTIONS] pattern
>
> Download and search for 'pattern' in diffoscope outputs of every unreproducible packages reported at https://reproducible.archlinux.org.
> This is useful to identify packages that are unreproducible because of a specific issue.
>
> OPTIONS
>     -h, --help            Show this message
>     -i, --ignore-case     Ignore case distinctions in patterns and input data
>
> Examples:
>     $ greposcope "gzip compressed data"
>     $ greposcope -i zipinfo
Diffoscope outputs are downloaded under `${TMPDIR:-/tmp}/greposcope-${UID}"`. Only diffoscope outputs that haven't been downloaded yet (as in, not found in `${TMPDIR:-/tmp}/greposcope-${UID}"`) are downloaded, so only the first run of the script downloads "world" (so we don't make a huge amount of …

Add greposcope: script for downloading and searching pattern in diffoscope output of unreproducible packages

---

package/greposcope

Allows to only print file names of diffoscope output that contains the pattern, so it's easier / quicker to identify which packages are affected by a specific issue.

Add the -l / --files-with-matches option to greposcope

---

admin/checkservices

Before:
```
usage checkservices [options]
description: check for updated files in a service
options:
-h: this help
-a/-A: auto confirmation (or not) (default: 0)
-l/-L: call (or not) systemd daemon-(reload|reexec) (default: 1)
-f/-F: display (or not) failed services before quit (default: 1)
-p/-P: call (or not) pacdiff before act (default: 1)
-r/-R: restart (or not) services with updated files (default: 1)
-s/-S: display (or not) status of restarted service (default: 1)
-u/-U: act (or not) on services in users slice (default: 0)
-m/-M: act (or not) on services in machine slice (default: 0)
-z/-Z: serialize (or not) action (default: 0)
-i 'service_name'.service: ignore a specific service (can be used multiple times)
```
After:
```
usage checkservices [options]
description: check for …
```

Update checkservices help message to be less confusing

---

Makefile
package/packages-signed-by

Intended to replace https://gitlab.archlinux.org/archlinux/archlinux-keyring/-/wikis/workflows/find-packages-signed-by-a-key

Add `packages-signed-by` script

---

Makefile
README.md

- Drop the custom made tarball: We now rely on [signed git tags](https://gitlab.archlinux.org/archlinux/packaging/packages/archlinux-contrib/-/commit/50905be547cd72eb1bcd1efab5b988e00781b883) for the package, which is more straightforward and transparent. IMO there's no need to keep creating this extra tarball.
- Move the whole release process into a single `release` target
- Switch to `gh`: `hub` throws an error (not sure if it's broken or expects something missing)
- Document the release process in the README

Update the release process
